version: '3.8'

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb
      - EDGE_PORT=4566
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: onewayticket
    ports:
      - "5432:5432"

  go-tests:
    build:
      dockerfile: Dockerfile-test
    depends_on:
      - localstack
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=onewayticket
      - DB_PORT=5432
